# Generated by Django 6.0.2 on 2026-02-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_seats_in_raws_cinemahall_seats_in_rows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seats_in_rows',
            new_name='seats_in_row',
        ),
    ]
